### ISSUE TITLE
Fails to download windows static libs

### ISSUE THREAD

**Issue by jacksondm33** [robotpy/robotpy-build#53]
The architecture should be "x86-64" but is being set to "x86". This creates a 404 error when downloading files.

**Comment by jacksondm33** [comment]
Well maybe this is a ctre specific problem. They don't provide "x86", only "x86-64". I don't know the build system very well, so I don't know where the fix for this would be.

**Comment by auscompgeek** [comment]
If your Python installation is x86, then it'll try to use x86 libraries. If you need x86-64 libraries, you need an x86-64 Python installation, as an x86 process cannot load x86-64 libraries.

**Comment by jacksondm33** [comment]
Yeah, I know. I was quick to target this as the problem when I think that ctre just doesn't host a 32-bit build. I wasn't familiar with the naming scheme used so that's why I didn't see this before.

**Comment by virtuald** [comment]
We should probably add something that warns the user when we know a platform isn't supported? Or just a better error message when the download failsOn Jan 24, 2020 7:25 PM, Jackson McClintock <notifications@github.com> wrote:Yeah, I know. I was quick to target this as the problem when I think that ctre just doesn't host a 32-bit build. I wasn't familiar with the naming scheme used so that's why I didn't see this before.
